import {
  LuPackage,
  LuTruck,
  LuCircleCheck,
  LuRotateCcw,
  LuCircleX,
  LuCreditCard,
  LuHouse,
  LuPackageCheck,
  LuBell,
} from "react-icons/lu"

export const customOrderUpdateTypes = {
  ORDER_UPDATED_PAID: {
    title: "Đơn hàng đã được thanh toán",
    message: "Cảm ơn bạn! Đơn hàng #${id} đã được xác nhận thanh toán thành công.",
    icon: LuCreditCard,
    color: "blue.500",
    badge: { colorScheme: "blue", label: "Order" },
  },
  ORDER_UPDATED_PROCESSING_FROM_PENDING: {
    title: "Đơn hàng đang được xử lý",
    message: "Chúng tôi đang chuẩn bị đơn hàng #${id} của bạn.",
    icon: LuPackage,
    color: "blue.500",
    badge: { colorScheme: "blue", label: "Order" },
  },
  ORDER_UPDATED_CANCELLED_FROM_PENDING: {
    title: "Đơn hàng bị hủy",
    message: "Đơn hàng #${id} đã bị hủy theo yêu cầu.",
    icon: LuCircleX,
    color: "red.500",
    badge: { colorScheme: "red", label: "Order" },
  },
  ORDER_UPDATED_PROCESSING_AFTER_PAID: {
    title: "Đơn hàng đang được xử lý",
    message: "Đơn hàng #${id} đã được thanh toán và đang được xử lý.",
    icon: LuPackageCheck,
    color: "blue.500",
    badge: { colorScheme: "blue", label: "Order" },
  },
  ORDER_UPDATED_CANCELLED_AFTER_PAID: {
    title: "Đơn hàng bị hủy sau khi thanh toán",
    message: "Đơn hàng #${id} đã được hủy, khoản thanh toán sẽ được hoàn lại.",
    icon: LuCircleX,
    color: "red.500",
    badge: { colorScheme: "red", label: "Order" },
  },
  ORDER_UPDATED_REFUNDED_AFTER_PAID: {
    title: "Hoàn tiền đơn hàng",
    message: "Khoản thanh toán cho đơn hàng #${id} đã được hoàn lại.",
    icon: LuRotateCcw,
    color: "yellow.500",
    badge: { colorScheme: "blue", label: "Hoàn tiền" },
  },
  ORDER_UPDATED_SHIPPING: {
    title: "Đơn hàng đang được giao",
    message: "Đơn hàng #${id} đã được gửi đi, vui lòng theo dõi quá trình vận chuyển.",
    icon: LuTruck,
    color: "blue.500",
    badge: { colorScheme: "blue", label: "Order" },
  },
  ORDER_UPDATED_REFUNDED_DURING_PROCESSING: {
    title: "Đơn hàng được hoàn tiền",
    message: "Đơn hàng #${id} đã được hoàn tiền trong quá trình xử lý.",
    icon: LuRotateCcw,
    color: "yellow.500",
    badge: { colorScheme: "blue", label: "Hoàn tiền" },
  },
  ORDER_UPDATED_DELIVERED: {
    title: "Đơn hàng đã được giao",
    message: "Đơn hàng #${id} đã được giao thành công!",
    icon: LuHouse,
    color: "green.500",
    badge: { colorScheme: "blue", label: "Order" },
  },
  ORDER_UPDATED_REFUNDED_IN_TRANSIT: {
    title: "Hoàn tiền khi đang giao",
    message: "Đơn hàng #${id} đã được hoàn tiền khi đang giao.",
    icon: LuRotateCcw,
    color: "yellow.500",
    badge: { colorScheme: "blue", label: "Hoàn tiền" },
  },
  ORDER_UPDATED_COMPLETED: {
    title: "Đơn hàng hoàn tất",
    message: "Cảm ơn bạn! Đơn hàng #${id} đã hoàn tất. Hãy đánh giá trải nghiệm của bạn nhé.",
    icon: LuCircleCheck,
    color: "green.500",
    badge: { colorScheme: "blue", label: "Order" },
  },
  ORDER_UPDATED_REFUNDED_AFTER_DELIVERED: {
    title: "Hoàn tiền sau khi giao",
    message: "Đơn hàng đã được hoàn tiền sau khi giao thành công.",
    icon: LuRotateCcw,
    color: "yellow.500",
    badge: { colorScheme: "blue", label: "Hoàn tiền" },
  },
  ORDER_UPDATED_REFUNDED_AFTER_COMPLETED: {
    title: "Hoàn tiền sau khi hoàn tất",
    message: "Một khoản hoàn tiền đã được xử lý sau khi đơn hàng hoàn tất.",
    icon: LuRotateCcw,
    color: "yellow.500",
    badge: { colorScheme: "blue", label: "Hoàn tiền" },
  },
}
