export const ORDER = {
  PENDING:    'PENDING',
  PAID:       'PAID',
  PROCESSING: 'PROCESSING',
  SHIPPING:   'SHIPPING',
  DELIVERED:  'DELIVERED',
  COMPLETED:  'COMPLETED',
  CANCELLED:  'CANCELLED',
  REFUNDED:   'REFUNDED'
}

export const ALLOWED = {
  [ORDER.PENDING]:    [ORDER.PAID, ORDER.CANCELLED],
  [ORDER.PAID]:       [ORDER.PROCESSING, ORDER.CANCELLED, ORDER.REFUNDED],
  [ORDER.PROCESSING]: [ORDER.SHIPPING, ORDER.REFUNDED],
  [ORDER.SHIPPING]:   [ORDER.DELIVERED, ORDER.REFUNDED],
  [ORDER.DELIVERED]:  [ORDER.COMPLETED, ORDER.REFUNDED],
  [ORDER.COMPLETED]:  [],
  [ORDER.CANCELLED]:  [],
  [ORDER.REFUNDED]:   []
}
